outputpath: experiments/clotho_v2
remark: pretraincnn_scst

data:
    raw_feat_csv: data/clotho_v2/dev_val/lms.csv
    fc_feat_csv: data/clotho_v2/dev_val/lms.csv
    attn_feat_csv: data/clotho_v2/dev_val/lms.csv
    caption_file: data/clotho_v2/dev_val/text.json

vocabulary: data/clotho_v2/dev_val/vocab.pkl
zh: False
dataloader_args:
    batch_size: 32
    num_workers: 4
train_percent: 90
augments: [timemask, freqmask]
distributed: False

encodermodel: CNN10QEncoder
encodermodel_args:
    embed_size: 512
decodermodel: RNNBahdanauAttnDecoder
decodermodel_args:
    embed_size: 512
    rnn_type: GRU
    num_layers: 1
    hidden_size: 512
    dropout: 0.5
model: Seq2SeqAttnModel
model_args: {}
modelwrapper: ScstWrapper

load_pretrained: True
pretrained: experiments/clotho_v2/Seq2SeqAttnModel/pretraincnn10_xe/seed_1/saved.pth

improvecriterion: score

optimizer: Adam
optimizer_args:
    lr: 0.00005
    weight_decay: 0.0
epochs: 100

